name: Deploy Backend Sync Nhanh Shopify

on:
  push:
    branches: [ main ] # Kiểm tra xem bạn dùng branch main hay master nhé

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }} # Bạn nhớ tạo Secret này là IP của VPS
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/BackendSyncNhanhWithShoptify
            git pull origin main
            npm install
            npm run build
            pm2 reload all 
